name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  quality_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage flake8 mypy black bandit safety

      - name: Lint with flake8
        run: flake8 .

      - name: Check formatting with black
        run: black --check .

      - name: Run mypy for static type checking
        run: mypy .

      - name: Security scan with bandit
        run: bandit -r .

      - name: Run tests with coverage
        run: |
          coverage run --source=. -m unittest discover -s tests
          coverage report --fail-under=50

      - name: Check for dependency vulnerabilities with safety
        run: safety check
