name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage codecov

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s graphorchestrator.tests
          coverage report --fail-under=85
          coverage xml  # Generate XML for Codecov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          name: python-coverage
          fail_ci_if_error: true
